### ISSUE TITLE
Upload step errors trying to delete tmp file

### ISSUE THREAD

**Issue by park896** [jenkinsci/windows-azure-storage-plugin#35] opened 2017-01-28 00:35 UTC
The upload task seems to have an issue where it can't delete the tmp archive.zip that is created. It appears to be coming from `tempPath.deleteRecursive();` method call at the very end of the upload method in [WAStorageClient.java](https://github.com/jenkinsci/windows-azure-storage-plugin/blob/master/src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStorageClient.java). In my setup, it is not important to cleanup the workspace after the build as the workspace is recreated with every build. Could you provide an optional boolean attribute to the upload task to skip the delete of temp files or alternatively figure out why the file is locked still.

Thanks for the help on the previous issue btw.

```
		upload(listener, blob, zipPath);
		// Make sure to note the new blob as an archive blob,
		// so that it can be specially marked on the azure storage page.
		archiveBlobs.add(new AzureBlob(blob.getName(), blob.getUri().toString().replace("http://", "https://"), md5hex, sizeInBytes));

		tempPath.deleteRecursive();
	    }

	} catch (Exception e) {
	    throw new WAStorageException(e.getMessage(), e.getCause());
	}
	return filesUploaded;
```

```
Uploaded blob with uri https://....blob.core.windows.net/.../archive.zip in 00:00:01.585 (HH:mm:ss.S)
ERROR: MicrosoftAzureStorage - Error occurred while uploading to Azure - ...
com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Unable to delete 'C:\...\artifactsArchive1192707576229944372.tmp\archive.zip'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at com.microsoftopentechnologies.windowsazurestorage.WAStorageClient.upload(WAStorageClient.java:363)
	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:289)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:59)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.FileSystemException: C:\...\artifactsArchive1192707576229944372.tmp\archive.zip: The process cannot access the file because it is being used by another process.
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
	at java.nio.file.Files.deleteIfExists(Unknown Source)
	at hudson.Util.tryOnceDeleteFile(Util.java:287)
	at hudson.Util.deleteFile(Util.java:243)
	at hudson.FilePath.deleteRecursive(FilePath.java:1209)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1218)
	at hudson.FilePath.deleteRecursive(FilePath.java:1200)
	at hudson.FilePath.access$1000(FilePath.java:195)
	at hudson.FilePath$14.invoke(FilePath.java:1179)
	at hudson.FilePath$14.invoke(FilePath.java:1176)
	at hudson.FilePath.act(FilePath.java:996)
	at hudson.FilePath.act(FilePath.java:974)
	at hudson.FilePath.deleteRecursive(FilePath.java:1176)
	at com.microsoftopentechnologies.windowsazurestorage.WAStorageClient.upload(WAStorageClient.java:359)
```

**Comment by park896** [comment] 2017-01-28 06:34
Additional Info: I've been using the zip archive feature for about 50 archive steps now and I'd say that around 25-35% of attempts fail with this error.

**Comment by roguishmountain** [comment] 2017-02-07 16:32
@park896 Which version of the plugin are you using?

**Comment by park896** [comment] 2017-02-10 14:30
Version 0.3.2. This bug would occur randomly and in some cases, the plugin even held on to the reference to the zip file for several minutes after the build completed so I could not even clean the workspace for the next build. I ended up zipping the files myself and then having this plugin upload my zip file instead of using the built in zip capability.

**Comment by 4eyecoder** [comment] 2017-03-22 09:12
I am experiencing the same thing in 0.3.4

**Comment by clguimanMSFT** [comment] 2017-04-07 16:31
I think it's a duplicate of #49 Can you try installing this plugin: http://devopspublicstorage.blob.core.windows.net/devops-jenkins/windows-azure-storage/clguimanMSFT/file-lock/5/windows-azure-storage.hpi ?

**Comment by chenkennt** [comment] 2018-01-25 04:24
Close it as it cannot repro now. Please feel free to open a new one if you still see this.

**Closed by chenkennt** 2018-01-25 04:24 UTC
