### ISSUE TITLE
"Download from Microsoft Azure Blob Storage" function not available

### ISSUE THREAD

**Issue by oneautomate** [jenkinsci/windows-azure-storage-plugin#37] opened 2017-02-09 20:46 UTC
Hi There,
I installed jenkin 2.32.2 with azure-storage-plugin 0.3.2.
There is no option "Download from Microsoft Azure Blob Storage" in build step, can you please help to take a look?

Here is the error in Jenkins:
Feb 09, 2017 7:48:48 PM WARNING hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error

Failed to instantiate Key[type=com.microsoftopentechnologies.windowsazurestorage.AzureStorageBuilder$AzureStorageBuilderDesc, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: hudson/plugins/copyartifact/BuildSelector
  at com.microsoftopentechnologies.windowsazurestorage.AzureStorageBuilder$AzureStorageBuilderDesc.<init>(AzureStorageBuilder.java:295)

1 error
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:424)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:386)
	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:377)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:472)
	at hudson.ExtensionList.load(ExtensionList.java:365)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
	at hudson.ExtensionList.getComponents(ExtensionList.java:168)
	at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:191)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
	at hudson.ExtensionList.iterator(ExtensionList.java:157)
	at jenkins.branch.CustomOrganizationFolderDescriptor.doAddSpecificDescriptors(CustomOrganizationFolderDescriptor.java:166)
	at jenkins.branch.CustomOrganizationFolderDescriptor.addSpecificDescriptors(CustomOrganizationFolderDescriptor.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: hudson/plugins/copyartifact/BuildSelector
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at hudson.model.Descriptor.<init>(Descriptor.java:288)
	at hudson.tasks.BuildStepDescriptor.<init>(BuildStepDescriptor.java:56)
	at com.microsoftopentechnologies.windowsazurestorage.AzureStorageBuilder$AzureStorageBuilderDesc.<init>(AzureStorageBuilder.java:295)
	at com.microsoftopentechnologies.windowsazurestorage.AzureStorageBuilder$AzureStorageBuilderDesc$$FastClassByGuice$$54a06dd3.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	... 30 more
Caused by: java.lang.ClassNotFoundException: hudson.plugins.copyartifact.BuildSelector
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1373)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more

Feb 09, 2017 7:48:49 PM INFO jenkins.InitReactorRunner$1 onAttained

I also found a similar case reported on Jenkins Jira:
https://issues.jenkins-ci.org/browse/JENKINS-41713?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27windows-azure-storage-plugin%27

**Comment by clguimanMSFT** [comment] 2017-02-09 21:07
Hi
This looks like a duplicate of #34 - You need to have the copyartifact plugin installed

**Closed by clguimanMSFT** 2017-02-09 21:07 UTC

**Comment by oneautomate** [comment] 2017-02-09 21:17
Thanks! That fixed it.
Can you please update the installation part in "readme.md"? It will be helpful for those who with the same issues.
